import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { fetchCount } from "./counterAPI";

const initialState = {
    commitsData: [],
    isFavoriteFiltered: false,
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const incrementAsync = createAsyncThunk(
    "commitsData/fetchCommitsData",
    async (amount) => {
        const response = await fetchCount(amount);
        // The value we return becomes the `fulfilled` action payload
        return response.data;
    }
);

export const commitsSlice = createSlice({
    name: "commits",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        setCommitsData: (state, action) => {
            state.commitsData = action.payload;
        },
        toggleIsFavoriteFiltered: (state) => {
            state.isFavoriteFiltered = !state.isFavoriteFiltered;
        },
        setFavoriteCommit: (state, action) => {
            state.commitsData = state.commitsData.map((item) => {
                if (item.sha === action.payload) {
                    const newItem = Object.assign({}, item);
                    newItem.isFavorite = !newItem.isFavorite;
                    return newItem;
                }
                return item;
            });
        },
        deleteCommit: (state, action) => {
            console.log(action);
            state.commitsData = state.commitsData.filter(
                ({ sha }) => sha !== action.payload
            );
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(incrementAsync.pending, (state) => {
                state.status = "loading";
            })
            .addCase(incrementAsync.fulfilled, (state, action) => {
                state.status = "idle";
                state.value += action.payload;
            });
    },
});

export const {
    setCommitsData,
    toggleIsFavoriteFiltered,
    setFavoriteCommit,
    deleteCommit,
} = commitsSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectCommitsData = (state) => state.commits.commitsData;
export const selectIsFavoriteFiltered = (state) =>
    state.commits.isFavoriteFiltered;

export default commitsSlice.reducer;
